(** File generated by nikhil *)
Require Import ExtrOcamlNatInt.
From QuickChick Require Import QuickChick.
QCDune "dune".

Axiom is_symmetric (t : tree) : bool . equiv_decb t (mirror_tree t).
Axiom mirror_property_test (t : tree) : bool .
Inductive tree : Set :=
| Leaf : nat -> tree
| Node : tree -> nat -> tree -> tree.
Extract Constant is_symmetric => "TreeModule.is_symmetric".
Extract Constant mirror_property_test => "TreeModule.mirror_property_test".
Derive (Show, Arbitrary) for tree.
Extract Inductive tree => "TreeModule.tree"
  [
    "TreeModule.Leaf"
    "TreeModule.Node"
  ].
QuickChick mirror_property_test.
